### ISSUE TITLE
jquery-ui-datepicker as Ember Data date

### ISSUE THREAD

**Issue by shicholas** [Gaurav0/ember-cli-jquery-ui#12]
Hello,

First and foremost thanks for this awesome library :). 

I've noticed that the ui-datepicker only adds values as strings and not as Date. I have a model with a `DS.attr('date')`, and feel that the ui-datepicker should return values that are compliant with a javascript Date Object. Currently, I can accomplish this with an observer like this:

``` js
  updateDate: function() {
    var date = window.moment(this.get("unparsedDate"));
    if (date.isValid()) {
      this.set("form.date", date.toDate());
    } else {
      this.set("form.date", null);
    }
  }.observes("unparsedDate"),
```

and in my view

``` hbs
{{jqui-datepicker value=unparsedDate}}
```

I am writing to see if you think this is a good idea to include javacript date parsing into this library. If so, I'll happily make the PR.

**Comment by Gaurav0** [comment]
With Ember 2.0 angle bracket components going to one way bindings by default and observers no longer considered "good", I'd like to make a few suggestions:

1. Create a 'parsedDate' property that is a computed property of unparsedDate.
2. See if you can use the actions up methodology to pass data out of the component.

**Comment by shicholas** [comment]
thanks for the prompt reply! I don't completely know what this entails, but I'll do some research and post back soon.

**Comment by shicholas** [comment]
is this kind of what you're referring to?

* creating an object that will have a computed parsedDate and and uparsedDate:

```js
export default Ember.Object.extend({
  unparsedDate: null

  parsedDate: function() {
    var date = window.moment(this.get('unparsedDate'));
    if (date.isValid()) {
      this.set('visitForm.visit.admitted_at', date.toDate());
    } else {
      this.set('visitForm.visit.admitted_at', null);
    }
  }.property('unparsedDate'),
});
```

* then creating these objects in my controller for use in my templates, with ``value=createdObject.unparsedDate``
* then reading the parsedDate properties in my actions where needed?

**Comment by shicholas** [comment]
I also tried creating a parsedValue property by extending the jquery-ui-datepicker, and using the ``value`` property, but that didn't seem right.

**Comment by Gaurav0** [comment]
So a computed property shouldn't have side effects, i.e. it shouldn't set anything.

And it is now considered best practice to use "data down, actions up" to pass data around.

**Comment by shicholas** [comment]
yes, from the docs it seems like a computed property should be read-only. So I guess you agree that the computed property on the object is better than trying to extend the datepicker class?

**Comment by Gaurav0** [comment]
Yes, I suppose that's true. Although if we can extend the datepicker class in a way consistent with the direction Ember itself is going in, I'm certainly open to ideas.

**Comment by shicholas** [comment]
I've been thinking about this, but no good idea yet (still can only think about observing the property from the component) sorry.

**Comment by shicholas** [comment]
How about something like this in your jqui-datepicker component:

```js
import Ember from 'ember';
import jquiDatepicker from 'ember-cli-jquery-ui/components/jqui-datepicker/component';

export default jquiDatepicker.extend({
  didInsertElement: function() {
    if (window.moment(this.get('model')).isValid()) {
      this.set('value', window.moment(this.get('model')).format('L'));
    }
    else {
      this.set('value', null);
    }
  },

  updateParsedValue: function() {
    var date = window.moment(this.get('value'));
    if (date.isValid()) {
      this.set('model', date.toDate());
    } else {
      this.set('model', null);
    }
  }.observes('value')
});
```

then the interface for the component becomes:

```hbs
{{jqui-datepicker model=visit.admittedAt class='visit-admitted_at'}}
```

what do you think?
