### ISSUE TITLE
Question: issues w/ jquery-ui-datepicker in component integration tests

### ISSUE THREAD

**Issue by shicholas** [Gaurav0/ember-cli-jquery-ui#13]
whoops sorry about no comment before I posted:

I have a component that uses a jquery-ui-datepicker, when I run the integration tests (from ember/ember-cli 1.13) I get: `TypeError: inst is undefined`. The datepicker is the only component here with that issue in my specs. I have tried `needs ['component:jqui-datepicker']` too to no avail. Because [it's not a function](https://github.com/Gaurav0/ember-cli-jquery-ui/blob/master/addon/mixins/jqui-widget.js#L24-L38) is there anything special I need to be aware of?

**Comment by Gaurav0** [comment]
Ember 1.13 broke the tests but the components still work.

**Comment by shicholas** [comment]
thanks, out of curiosity which tests are you referring to?
