### ISSUE TITLE
Can't install addon. Tag/branch 1.11.1=jquery-ui#1.11.1# does not exist

### ISSUE THREAD

**Issue by mattmazzola** [Gaurav0/ember-cli-jquery-ui#14]
Hi,

I've tried installing with ember-cli 1.13.5 and 1.13.7 and get the same error.

It seems like the tag 1.11.1 does exist here:
https://github.com/components/jqueryui/tree/1.11.1

Perhaps somehow the way bower package name is formatted is incorrect, although it looks like this file has never changed and this must have worked previously.

in https://github.com/Gaurav0/ember-cli-jquery-ui/blob/master/blueprints/ember-cli-jquery-ui/index.js
This addon is pretty simple and this line looks correct but somehow it's not working.
`return this.addBowerPackageToProject('jquery-ui#1.11.1');`

Error:
```
ember install ember-cli-jquery-ui
version: 1.13.7
Installed packages for tooling via npm.
installing ember-cli-jquery-ui
Installing browser packages via Bower...
  not-cached git://github.com/components/jqueryui.git#1.11.1=jquery-ui#1.11.1#
Tag/branch 1.11.1=jquery-ui#1.11.1# does not exist
Error: Tag/branch 1.11.1=jquery-ui#1.11.1# does not exist
```

**Comment by Gaurav0** [comment]
Tried fixing by upgrading to jquery-ui 1.11.4; didn't work.

**Comment by Gaurav0** [comment]
@stefanpenner, do you know if is this a bug in ember-cli or bower?

**Comment by stefanpenner** [comment]
Cc @mike-north

**Comment by mike-north** [comment]
Correct use of `addBowerPackageToProject` involves two arguments

```js
/**
  Used to add a package to the projects `bower.json`.
  Generally, this would be done from the `afterInstall` hook, to
  ensure that a package that is required by a given blueprint is
  available.
  `localPackageName` and `target` may be thought of as equivalent
  to the key-value pairs in the `dependency` or `devDepencency`
  objects contained within a bower.json file.
  Examples:
  addBowerPackageToProject('jquery', '~1.11.1');
  addBowerPackageToProject('old_jquery', 'jquery#~1.9.1');
  addBowerPackageToProject('bootstrap-3', 'http://twitter.github.io/bootstrap/assets/bootstrap');
  @method addBowerPackageToProject
  @param {String} localPackageName
  @param {String} target
  @param {Object} installOptions
  @return {Promise}
*/
Blueprint.prototype.addBowerPackageToProject = function(localPackageName, target, installOptions) {
  var packageObject = bowEpParser.json2decomposed(localPackageName, target);
  return this.addBowerPackagesToProject([packageObject], installOptions);
};
```
source: https://github.com/ember-cli/ember-cli/blob/bec8ecba39b44daa01171fe83dd74f7767c8d8ac/lib/models/blueprint.js#L968-L994

If `return this.addBowerPackageToProject('jquery-ui#1.11.1');` worked at some time in the past, it's because of a bug. If you change to `return this.addBowerPackageToProject('jquery-ui', '1.11.1');` everything should work fine

**Comment by stefanpenner** [comment]
@mike-north lets split on '#' in ember-cli, but warn that the form you mention is correct.
