### ISSUE TITLE
Resolver doesn't seem to be picking up components

### ISSUE THREAD

**Issue by drewclauson** [Gaurav0/ember-cli-jquery-ui#15]
When I do an ember install, the packages install fine, but when I try to use a component, I get an error saying that jqui-datepicker is not found.  Looking at the logs, it appears to me that the resolver is not finding the components when a component exists under the app/jqui-datepicker/component.js structure.  I moved that file to app/jqui-datepicker.js and they resolved correctly.

I'm on CLI 1.13.8 and ember 2.1

I don't have a long history with Ember - perhaps the new ember-resolver doesn't resolve the app/jqui-datepicker/component.js as before?  I'd be happy to issue a PR to rename / reorganize app folder, but want to make sure that'll actually help before doing so.

**Comment by Gaurav0** [comment]
Are you using podmoduleprefix?

**Comment by drewclauson** [comment]
Yep, and I even looked at the other issue that is open and didn't even think about it being an issue.
