### ISSUE TITLE
can u give an example on how to use the event ?

### ISSUE THREAD

**Issue by yanzixiang** [Gaurav0/ember-cli-jquery-ui#18]
uiEvents: ['activate', 'beforeActivate', 'beforeLoad', 'create', 'load'],

list as this.

```javascript
{{#jqui-tabs load=(action "tabsload")}}
```
doesn't work.

**Comment by Gaurav0** [comment]
Closure actions do not work.

You would have to use traditional actions, like this: 

    {{#jqui-tabs load="tabsLoad"}}
