### ISSUE TITLE
consider putting the example app within the test/dummy/* app

### ISSUE THREAD

**Issue by stefanpenner** [Gaurav0/ember-cli-jquery-ui#3]
https://github.com/Gaurav0/ember-cli-jquery-ui

This keeps it self contained, and visiting `ember server` in the addon will display the demo.

This also becomes a great place to add unit/integration/acceptance tests

**Comment by seawatts** [comment]
@Gaurav0 I don't think he meant for it to be served with heroku. He was talking more about actually adding a dummy application so that when you checkout your project and run ember serve you can see the dummy app working.

**Comment by Gaurav0** [comment]
There are no points on Ember Observer for having a dummy application.

I really don't want to maintain a dummy app in addition to my separate example application.

**Comment by seawatts** [comment]
Oh, I didn't see you had a example app as well.

Also, my mistake about the emberobserver points.
