### ISSUE TITLE
If I apply a class to datepicker it stops working

### ISSUE THREAD

**Issue by pedropaf** [Gaurav0/ember-cli-jquery-ui#7]
I can add this to my template:

{{jqui-datepicker value=date}}

It works fine, but I'm using twitter bootstrap for styling, so I want to apply a couple of classes to the input, if I change the previous snippet to this:

{{jqui-datepicker value=date class="form-control input-lg"}}

the styles are applied, but the datepicker doesn't work anymore.

**Comment by Gaurav0** [comment]
Tried the following:

ember new example-app
cd example-app
ember install ember-cli-jquery-ui
ember install ember-bootstrap

Then I appended

    {{jqui-datepicker value=date class="form-control input-lg"}} {{date}}

to app/templates/application.js

Worked for me.
