### ISSUE TITLE
Error in datepicker update option properties

### ISSUE THREAD

**Issue by sasknot** [Gaurav0/ember-cli-jquery-ui#8]
I have two datepickers like this:

`{{jqui-datepicker value=dateFrom dateFormat="dd/mm/yy" maxDate=dateTo class="form-control datepicker" placeholder="De"}}`

`{{jqui-datepicker value=dateTo dateFormat="dd/mm/yy" minDate=dateFrom maxDate=today class="form-control datepicker" placeholder="Até"}}`

But when a update dateFrom or dateTo props, I get this error:

`Uncaught TypeError: Cannot read property 'option' of undefined`
File: addon/mixins/jqui-widget.js
Line: 81

My workaround for this was to create another two properties called dateFromStatic and dateToStatic which don't change the value, and then set onClose prop with the manually callback from the jQueryUI example: http://jqueryui.com/datepicker/#date-range

Also, sorry for the bad english... =P

**Comment by Gaurav0** [comment]
Can you try latest master and see if your issue is fixed?

**Comment by sasknot** [comment]
Perfect, now it's working. =)
Thank you very much.

**Comment by sasknot** [comment]
Now I'm getting this error when a change the page:

`Uncaught TypeError: ui._destroy is not a function`
File: addon/mixins/jqui-widget.js
Line: 63

**Comment by Gaurav0** [comment]
Are you using latest master, 0930628375f59a59deb97edbe32571a4743b8918?

**Comment by sasknot** [comment]
Sorry, didn't see that commit... now it's working perfectly.
Thanks!

**Comment by seawatts** [comment]
Can this be closed?
